### ISSUE TITLE
Objections to ``KnownNat`` constraints on generalized ``concatMap``?

### ISSUE THREAD

**Issue by kozross** [expipiplus1/vector-sized#66]
I'm working on #62 (specifically the generalized ``concatMap``). I'm trying carefully to ensure that the signature is as backwards-compatible as possible (that is, I don't mandate constraints that would have failed any existing uses of it), but this is proving difficult to do in an efficient way. 

I could make this much better by introducing ``KnownNat`` constraints to the signature, but that would obviously be a much more breaking change. Given that the PVP mandates new instances be considered breaking, and I'm already adding ``Hashable`` instances, this means we're already going to have to bump the version majorly when we merge this. As a result, I don't think it's _that_ big a deal, and would help massively.

That being said, I'd like some feedback on this before I write anything. @mstksg, @expipiplus1 - your opinions on this would be very important to me!

**Comment by mstksg** [comment]
You actually shouldn't ever need to require a `KnownNat` constraint if you ever *receive* a `Vector n a`.  That's because `Vector n a`, as a value, *contains* information about its length, so you can always reflect out `KnownNat`.  That's what `knownLength` dóe:

```haskell
knownLength
    :: Vector n a
    -> (KnownNat n => r)
    -> r
```

`knownLength` reifies the length out of the vector.

So, you really only need `KnownNat` if you don't have any parameters from the user that can provide length information -- for example, functions like `replicate :: KnownNat n => a -> Vector n a`.

`concatMap` then shouldn't need `KnownNat` in practice because the user provides the `Vector n a` (giving `n`) and also functions to provide `Vector m a` (giving `m`).  So you could always just use `knownLength` to extract out the lengths from these vectors.

However, in the end, none of this should be necessary, I think, because you could just coerce everything out anyway (unsafely):

```haskell
concatMap :: (a -> Vector m b) -> Vector n a -> Vector (n * m) b
concatMap f = coerce (Unsized.concatMap (coerce f))
```

(Or, if not with coercions, just manually wrapping and unwrapping the `Vector` newtype)

**Comment by kozross** [comment]
@mstksg Thanks for clearing that up!
