### ISSUE TITLE
Binary instances for Vectors?

### ISSUE THREAD

**Issue by kozross** [expipiplus1/vector-sized#81]
I think it's a useful thing to have - what are your thoughts @mstksg and @expipiplus1?

**Comment by mstksg** [comment]
Good question. Considering *binary* is a part of ghc boot libraries, I don't see a big reason why there shouldn't be one.

**Comment by mstksg** [comment]
One reason I thought of as soon as I sent that reply -- the original `vector` type does not have a `Binary` instance (it's commonly imported as an [orphan instance from an external package](http://hackage.haskell.org/package/vector-binary-instances)), so it might not make sense if we consider this package as a "strict re-export" of the *vector* package.

However the binary story for plain vector is admittedly a mess because of the orphan instance package...and we also have bunches of instances that aren't from the original *vector*...so this I think this reason is not a good one.

**Comment by kozross** [comment]
I'm of the opinion that providing our own instance of ``Binary`` is fine. Arguably, _not_ providing an instance of ``Binary`` for (unsized) vectors is a mistake on the part of the ``vector`` maintainers, and I see no reason to carry that forward.

**Comment by expipiplus1** [comment]
Sounds good to me, @kozross if you open a PR in the next couple of days I'll release all the recent changes as 1.4.0.0

**Comment by kozross** [comment]
@expipiplus1 No problem, on it!

**Comment by expipiplus1** [comment]
Merged!

**Comment by expipiplus1** [comment]
Released as v1.4.0.0
